openapi: 3.0.0
info:
  title: API
  description: OpenAPI v3 powered API for Riverscout
  version: '0.3'
paths:
  /deviceInfo:
    get:
      x-swagger-router-controller: deviceController
      operationId: getDeviceInfo
      tags:
        - Device
      description: Returns data for the specified device within the times specified
      parameters:
        - name: deviceID
          in: query
          description: The database ID of the device to get data for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        default:
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /deviceGroups:
    get:
      x-swagger-router-controller: deviceGroupController
      operationId: getDeviceGroups
      tags:
        - Device Group
      description: Returns all the device groups for the specified country code
      parameters:
        - name: countryCode
          in: query
          description: Return all groups in this country
          schema:
            type: string
      responses:
        '200':
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        default:
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'                   
  /addDeviceReading:
    post:
      x-swagger-router-controller: deviceReadingController
      tags:
        - Device Reading
      description: Adds a reading for a device
      operationId: addSensorReading
      responses:
        '201':
          description: Added reading
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - sigfoxID
                - rawHexString
                - timestamp
              properties:
                sigfoxID:
                  type: string
                  description: The Sigfox ID for a device
                rawHexString:
                  type: string
                  description: The raw hex data coming from the Sigfox backend 
                timestamp:
                  type: string
                  description: UNIX timestamp coming from the Sigfox backend
        description: >-
          Adds a measurement for a specific device    
  /addCountry:
    post:
      x-swagger-router-controller: countryCodeController
      tags:
        - Country Codes
      description: Adds a new 'country' with an ID and a country code
      operationId: addNewCountry
      responses:
        '201':
          description: Added country
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - countryName
                - code
                - countryID
              properties:
                countryName:
                  type: string
                  description: The name of this country eg 'Ireland'
                countryID:
                  type: number
                  description: A numeric ID for a country. Must be unique 
                code:
                  type: string
                  description: Two character code eg; 'IE', 'FR', 'DE'
        description: >-
          Adds a measurement for a specific device             
  /addDeviceGroup:
    post:
      x-swagger-router-controller: deviceGroupController
      tags:
        - Device Group
      description: Adds a group for devices
      operationId: addDeviceGroup
      responses:
        '201':
          description: Created new group
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - groupLat
                - groupLong
                - groupName
              properties:
                groupLat:
                  type: number
                groupLong:
                  type: number
                groupName:
                  type: string
        description: >-
          Creates a device group with the specified parameters.        
  /addDevice:
    post:
      x-swagger-router-controller: deviceController
      tags:
        - Device
      description: Adds a new device (Sigfox/NBIoT)
      operationId: addNewDevice
      responses:
        '201':
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - displayName
                - gpsLong
                - gpsLat
                - countryCode
                - sigfoxID
                - installDate
                - replacementDate
                - reportingFreq
                - groupID
                - downlinkStatus
              properties:
                displayName:
                  type: string
                  description: "Name to display in front end"
                gpsLong:
                  type: number
                  format: double               
                  description: "GPS longitude of the gauge install location"
                gpsLat:
                  type: number
                  format: double
                  description: "GPS latitude of the gauge install location"
                countryCode:
                  type: string
                  description: "Uses the same codes as web domains. Eg: IE => Ireland"
                sigfoxID:
                  type: string
                  description: "Sigfox ID as generated by the Sigfox backend"
                installDate:
                  type: string
                  description: "Install date of device. Please use UTC format. Eg: 2018-09-09T14:00:00Z"
                replacementDate:
                  type: string
                  description: "UTC format date of the expected date the device is to be replaced"                  
                EOLDate:
                  type: string
                  description: "UTC format date of the time a device was actuallly replaced"                  
                reportingFreq:
                  type: string
                  description: "how often (in minutes) the device is expected to send up data"  
                groupID:
                  type: string
                  description: "ID of the group this device is in"
                activeStatus:
                  type: boolean
                  description: "Device active status"
                  default: true
                downlinkEnabled:
                  type: boolean
                  description: "Whether the device allows data to be sent to it or not."
                  
        description: >-
          Pushes Sigfox device data to the database with the device ID and
          timestamp.              
servers:
  - url: /api
components:
  schemas:
    Success:
      properties:
        msg:
          type: string
    Error:
      properties:
        message:
          type: string
      required:
        - message
